# Generated by Django 5.0.4 on 2024-09-03 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewApostila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('apostilas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='apostilas.apostila')),
            ],
        ),
    ]
